package com.rosin.manager.model;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.dept_id
     *
     * @mbg.generated
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.dept_name
     *
     * @mbg.generated
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.dept_leaderId
     *
     * @mbg.generated
     */
    private Integer deptLeaderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.company_id
     *
     * @mbg.generated
     */
    private Integer companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated
     */
    public Department(Integer deptId, String deptName, Integer deptLeaderid, Integer companyId) {
        this.deptId = deptId;
        this.deptName = deptName;
        this.deptLeaderid = deptLeaderid;
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.dept_id
     *
     * @return the value of department.dept_id
     *
     * @mbg.generated
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.dept_name
     *
     * @return the value of department.dept_name
     *
     * @mbg.generated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.dept_leaderId
     *
     * @return the value of department.dept_leaderId
     *
     * @mbg.generated
     */
    public Integer getDeptLeaderid() {
        return deptLeaderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.company_id
     *
     * @return the value of department.company_id
     *
     * @mbg.generated
     */
    public Integer getCompanyId() {
        return companyId;
    }
}