package com.rosin.manager.model;

import java.util.Date;

public class Feedback {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.feedback_id
     *
     * @mbg.generated
     */
    private Integer feedbackId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.feedback_time
     *
     * @mbg.generated
     */
    private Date feedbackTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.feedback_content
     *
     * @mbg.generated
     */
    private String feedbackContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbg.generated
     */
    public Feedback(Integer feedbackId, Integer userId, Date feedbackTime, String email, Integer status, String feedbackContent) {
        this.feedbackId = feedbackId;
        this.userId = userId;
        this.feedbackTime = feedbackTime;
        this.email = email;
        this.status = status;
        this.feedbackContent = feedbackContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.feedback_id
     *
     * @return the value of feedback.feedback_id
     *
     * @mbg.generated
     */
    public Integer getFeedbackId() {
        return feedbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.user_id
     *
     * @return the value of feedback.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.feedback_time
     *
     * @return the value of feedback.feedback_time
     *
     * @mbg.generated
     */
    public Date getFeedbackTime() {
        return feedbackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.email
     *
     * @return the value of feedback.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.status
     *
     * @return the value of feedback.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.feedback_content
     *
     * @return the value of feedback.feedback_content
     *
     * @mbg.generated
     */
    public String getFeedbackContent() {
        return feedbackContent;
    }
}